---
title: "Covid_STATS"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(maps) 
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
gisaid_csv <- read.csv("All gisaid retreive 20230911.csv")
```

```{r, fig.width = 10, fig.height = 4}

#Remove the 39 sample that were not submitted by our lab: to find them filter the Passage column to select Nasopharyngeal swab and Vero then remove those rows. 
# Lineage breakdown by month
lineage_breakdown <- gisaid_csv %>% 
  filter(Passage != "Nasopharyngeal swab" && Passage != "Vero") %>%
  select(Collection.date, Lineage) %>%
  mutate(Lineage = ifelse(Lineage == "BA.1.617.2", 'AY+BA.1.617.2', Lineage)) %>%
  mutate(Lineage_Group = case_when(Lineage == "AY+BA.1.617.2" ~ 'AY+BA.1.617.2',
                        grepl("AY", Lineage) ~ 'AY+BA.1.617.2',
                        grepl("BA.1", Lineage) ~ 'BA.1.1.529+BA.1',
                        grepl("BA.2", Lineage) ~ 'BA.2*+BA.3*',
                        grepl("BA.3", Lineage) ~ 'BA.2*+BA.3*',
                        grepl("BA.4", Lineage) ~ 'BA.4*',
                        grepl("BA.5", Lineage) ~ 'BA.5*',
                        grepl("XBB.1.5", Lineage) ~ 'XBB.1.5*',
                        grepl("XBB.1.16", Lineage) ~ 'XBB.1.16*',
                        grepl("XBB.1.9", Lineage) ~ 'XBB.1.9*',
                        grepl("XBB.2.3", Lineage) ~ 'XBB.2.3*',
                        grepl("CH.1.1", Lineage) ~ 'CH.1.1*',
                        grepl("BF", Lineage) ~ 'Non_BA',
                        grepl("BE", Lineage) ~ 'Non_BA',
                        grepl("BG", Lineage) ~ 'Non_BA',
                        grepl("BK", Lineage) ~ 'Non_BA',
                        grepl("BM", Lineage) ~ 'Non_BA',
                        grepl("BN", Lineage) ~ 'Non_BA',
                        grepl("BQ", Lineage) ~ 'Non_BA',
                        grepl("BR", Lineage) ~ 'Non_BA',
                        grepl("BW", Lineage) ~ 'Non_BA',
                        grepl("BU", Lineage) ~ 'Non_BA',
                        grepl("CA", Lineage) ~ 'Non_BA',
                        grepl("CD", Lineage) ~ 'Non_BA',
                        grepl("CH", Lineage) ~ 'Non_BA',
                        grepl("CK", Lineage) ~ 'Non_BA',
                        grepl("CL", Lineage) ~ 'Non_BA',
                        grepl("CM", Lineage) ~ 'Non_BA',
                        grepl("CN", Lineage) ~ 'Non_BA',
                        grepl("CR", Lineage) ~ 'Non_BA',
                        grepl("CV", Lineage) ~ 'Non_BA',
                        grepl("CZ", Lineage) ~ 'Non_BA',
                        grepl("CN", Lineage) ~ 'Non_BA',
                        grepl("DN", Lineage) ~ 'Non_BA',
                        grepl("DR", Lineage) ~ 'Non_BA',
                        grepl("EB", Lineage) ~ 'Non_BA',
                        grepl("ED", Lineage) ~ 'Non_BA',
                        grepl("EE", Lineage) ~ 'Non_BA',
                        grepl("EF", Lineage) ~ 'Non_BA',
                        grepl("EW", Lineage) ~ 'Non_BA',
                        grepl("EY", Lineage) ~ 'Non_BA',
                        grepl("FA", Lineage) ~ 'Non_BA',
                         )
                      )   %>%
  filter(!is.na(Lineage_Group)) %>%
  mutate(Collection.date = as.Date(Collection.date, format = "%Y-%m-%d")) %>%
  group_by(month = lubridate::floor_date(Collection.date, "month"), Lineage_Group) %>%
  filter(month != '1905-07-01') %>%
  summarize(count = n())

ggplot(lineage_breakdown, aes(fill = Lineage_Group, y = count, x = month)) + 
    geom_bar(position="fill", stat="identity") +
    scale_y_continuous(labels = scales::comma)+
    ggtitle("GISAID VBM and non BA Lineage Proportions by Collection Date")

ggplot(lineage_breakdown, aes(fill = Lineage_Group, y = count, x = month, label = count)) + 
    geom_bar(stat="identity") +
    scale_y_continuous(labels = scales::comma)+
    ggtitle("GISAID VBM Lineage Counts by Collection Date")
```

```{r, fig.width = 10, fig.height = 8}
#Lineage breakdown by county
count_by_county <- gisaid_csv %>% 
  filter(Passage != "Nasopharyngeal swab" && Passage != "Vero") %>%
  select(City, Lineage) %>%
  mutate(subregion = tolower(str_remove(City, ' County'))) %>%
  group_by(subregion) %>%
  summarize(count = n())
  
counties_data <- map_data("county", region = "texas")

merged <- inner_join(counties_data, count_by_county, by = "subregion")

# Create a Choropleth map of Texas
q <- qplot(long, lat, data = counties_data, geom = "polygon", group = group, fill = group)
g <- q + geom_polygon(data=merged, 
            aes(x=long, y=lat, group=group, fill = count), 
            color="black", size = 0.2) + 
  
      scale_fill_continuous(name="Sequence Count", low = "lightblue", 
            na.value = "grey50") +
  
      labs(title="Sequence Count by County in Texas") 
g


#Lineage breakdown by county
lineage_by_county <- gisaid_csv %>% 
  filter(Passage != "Nasopharyngeal swab" && Passage != "Vero") %>%
  select(City, Lineage) %>%
  mutate(subregion = tolower(str_remove(City, ' County'))) %>%
  mutate(Lineage = ifelse(Lineage == "BA.1.617.2", 'AY+BA.1.617.2', Lineage)) %>%
  mutate(Lineage_Group = case_when(Lineage == "AY+BA.1.617.2" ~ 'AY+BA.1.617.2',
                        grepl("AY", Lineage) ~ 'AY+BA.1.617.2',
                        grepl("BA.1", Lineage) ~ 'BA.1.1.529+BA.1',
                        grepl("BA.2", Lineage) ~ 'BA.2*+BA.3*',
                        grepl("BA.3", Lineage) ~ 'BA.2*+BA.3*',
                        grepl("BA.4", Lineage) ~ 'BA.4*',
                        grepl("BA.5", Lineage) ~ 'BA.5*',
                        grepl("XBB.1.5", Lineage) ~ 'XBB.1.5*',
                        grepl("XBB.1.16", Lineage) ~ 'XBB.1.16*',
                        grepl("XBB.1.9", Lineage) ~ 'XBB.1.9*',
                        grepl("XBB.2.3", Lineage) ~ 'XBB.2.3*',
                        grepl("CH.1.1", Lineage) ~ 'CH.1.1*',
                        grepl("BF", Lineage) ~ 'Non_BA',
                        grepl("BE", Lineage) ~ 'Non_BA',
                        grepl("BG", Lineage) ~ 'Non_BA',
                        grepl("BK", Lineage) ~ 'Non_BA',
                        grepl("BM", Lineage) ~ 'Non_BA',
                        grepl("BN", Lineage) ~ 'Non_BA',
                        grepl("BQ", Lineage) ~ 'Non_BA',
                        grepl("BR", Lineage) ~ 'Non_BA',
                        grepl("BW", Lineage) ~ 'Non_BA',
                        grepl("BU", Lineage) ~ 'Non_BA',
                        grepl("CA", Lineage) ~ 'Non_BA',
                        grepl("CD", Lineage) ~ 'Non_BA',
                        grepl("CH", Lineage) ~ 'Non_BA',
                        grepl("CK", Lineage) ~ 'Non_BA',
                        grepl("CL", Lineage) ~ 'Non_BA',
                        grepl("CM", Lineage) ~ 'Non_BA',
                        grepl("CN", Lineage) ~ 'Non_BA',
                        grepl("CR", Lineage) ~ 'Non_BA',
                        grepl("CV", Lineage) ~ 'Non_BA',
                        grepl("CZ", Lineage) ~ 'Non_BA',
                        grepl("CN", Lineage) ~ 'Non_BA',
                        grepl("DN", Lineage) ~ 'Non_BA',
                        grepl("DR", Lineage) ~ 'Non_BA',
                        grepl("EB", Lineage) ~ 'Non_BA',
                        grepl("ED", Lineage) ~ 'Non_BA',
                        grepl("EE", Lineage) ~ 'Non_BA',
                        grepl("EF", Lineage) ~ 'Non_BA',
                        grepl("EW", Lineage) ~ 'Non_BA',
                        grepl("EY", Lineage) ~ 'Non_BA',
                        grepl("FA", Lineage) ~ 'Non_BA',
                         )
                      )   %>%
  filter(!is.na(Lineage_Group)) %>%
  group_by(subregion, Lineage_Group) %>%
  summarize(count = n())

merged <- inner_join(counties_data, lineage_by_county, by = "subregion")
  

# Create a Choropleth map of Texas

q <- qplot(long, lat, data = counties_data, geom = "polygon", group = group, fill = group)
plotmap <- function(l, merged, q){
lineage <- merged %>% filter(Lineage_Group == l)
g <- q +
      geom_polygon(data = lineage, aes(x=long, y=lat, group=group, fill = count), 
            size = 0.2) + 
  
      scale_fill_continuous(name="Sequence Count", low = "lightblue",
            na.value = "grey70") +
  
      labs(title=paste(l))
print(g)
}
plotmap("AY+BA.1.617.2", merged, q)
plotmap("BA.2*+BA.3*", merged, q)

```